/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/_auth/callback'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRecurringRouteImport } from './routes/_app/recurring'
import { Route as AppPricingRouteImport } from './routes/_app/pricing'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppMembersRouteImport } from './routes/_app/members'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppFundsRouteImport } from './routes/_app/funds'
import { Route as AppBreakdownRouteImport } from './routes/_app/breakdown'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppGroupsIndexRouteImport } from './routes/_app/groups/index'
import { Route as AppExpensesIndexRouteImport } from './routes/_app/expenses/index'
import { Route as AppExpensesNewRouteImport } from './routes/_app/expenses/new'
import { Route as AppExpensesExpenseIdRouteImport } from './routes/_app/expenses/$expenseId'
import { Route as AppGroupsGroupIdEditRouteImport } from './routes/_app/groups/$groupId.edit'
import { Route as AppExpensesExpenseIdEditRouteImport } from './routes/_app/expenses/$expenseId.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/index.lazy').then((d) => d.Route))
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/invite.$token.lazy').then((d) => d.Route))
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/templates.lazy').then((d) => d.Route),
)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/settings.lazy').then((d) => d.Route))
const AppRecurringRoute = AppRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/recurring.lazy').then((d) => d.Route),
)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/pricing.lazy').then((d) => d.Route))
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/overview.lazy').then((d) => d.Route))
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/onboarding.lazy').then((d) => d.Route),
)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/members.lazy').then((d) => d.Route))
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/import.lazy').then((d) => d.Route))
const AppFundsRoute = AppFundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/funds.lazy').then((d) => d.Route))
const AppBreakdownRoute = AppBreakdownRouteImport.update({
  id: '/breakdown',
  path: '/breakdown',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/breakdown.lazy').then((d) => d.Route),
)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/analytics.lazy').then((d) => d.Route),
)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/activity.lazy').then((d) => d.Route))
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/groups/index.lazy').then((d) => d.Route),
)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/expenses/index.lazy').then((d) => d.Route),
)
const AppExpensesNewRoute = AppExpensesNewRouteImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/expenses/new.lazy').then((d) => d.Route),
)
const AppExpensesExpenseIdRoute = AppExpensesExpenseIdRouteImport.update({
  id: '/expenses/$expenseId',
  path: '/expenses/$expenseId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/expenses/$expenseId.lazy').then((d) => d.Route),
)
const AppGroupsGroupIdEditRoute = AppGroupsGroupIdEditRouteImport.update({
  id: '/groups/$groupId/edit',
  path: '/groups/$groupId/edit',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/groups/$groupId.edit.lazy').then((d) => d.Route),
)
const AppExpensesExpenseIdEditRoute =
  AppExpensesExpenseIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppExpensesExpenseIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/expenses/$expenseId.edit.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/activity': typeof AppActivityRoute
  '/analytics': typeof AppAnalyticsRoute
  '/breakdown': typeof AppBreakdownRoute
  '/funds': typeof AppFundsRoute
  '/import': typeof AppImportRoute
  '/members': typeof AppMembersRoute
  '/onboarding': typeof AppOnboardingRoute
  '/overview': typeof AppOverviewRoute
  '/pricing': typeof AppPricingRoute
  '/recurring': typeof AppRecurringRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/callback': typeof AuthCallbackRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/expenses/$expenseId': typeof AppExpensesExpenseIdRouteWithChildren
  '/expenses/new': typeof AppExpensesNewRoute
  '/expenses/': typeof AppExpensesIndexRoute
  '/groups/': typeof AppGroupsIndexRoute
  '/expenses/$expenseId/edit': typeof AppExpensesExpenseIdEditRoute
  '/groups/$groupId/edit': typeof AppGroupsGroupIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/activity': typeof AppActivityRoute
  '/analytics': typeof AppAnalyticsRoute
  '/breakdown': typeof AppBreakdownRoute
  '/funds': typeof AppFundsRoute
  '/import': typeof AppImportRoute
  '/members': typeof AppMembersRoute
  '/onboarding': typeof AppOnboardingRoute
  '/overview': typeof AppOverviewRoute
  '/pricing': typeof AppPricingRoute
  '/recurring': typeof AppRecurringRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/callback': typeof AuthCallbackRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/expenses/$expenseId': typeof AppExpensesExpenseIdRouteWithChildren
  '/expenses/new': typeof AppExpensesNewRoute
  '/expenses': typeof AppExpensesIndexRoute
  '/groups': typeof AppGroupsIndexRoute
  '/expenses/$expenseId/edit': typeof AppExpensesExpenseIdEditRoute
  '/groups/$groupId/edit': typeof AppGroupsGroupIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/activity': typeof AppActivityRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/breakdown': typeof AppBreakdownRoute
  '/_app/funds': typeof AppFundsRoute
  '/_app/import': typeof AppImportRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/recurring': typeof AppRecurringRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_auth/callback': typeof AuthCallbackRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/expenses/$expenseId': typeof AppExpensesExpenseIdRouteWithChildren
  '/_app/expenses/new': typeof AppExpensesNewRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
  '/_app/expenses/$expenseId/edit': typeof AppExpensesExpenseIdEditRoute
  '/_app/groups/$groupId/edit': typeof AppGroupsGroupIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/analytics'
    | '/breakdown'
    | '/funds'
    | '/import'
    | '/members'
    | '/onboarding'
    | '/overview'
    | '/pricing'
    | '/recurring'
    | '/settings'
    | '/templates'
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/invite/$token'
    | '/expenses/$expenseId'
    | '/expenses/new'
    | '/expenses/'
    | '/groups/'
    | '/expenses/$expenseId/edit'
    | '/groups/$groupId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/analytics'
    | '/breakdown'
    | '/funds'
    | '/import'
    | '/members'
    | '/onboarding'
    | '/overview'
    | '/pricing'
    | '/recurring'
    | '/settings'
    | '/templates'
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/invite/$token'
    | '/expenses/$expenseId'
    | '/expenses/new'
    | '/expenses'
    | '/groups'
    | '/expenses/$expenseId/edit'
    | '/groups/$groupId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/activity'
    | '/_app/analytics'
    | '/_app/breakdown'
    | '/_app/funds'
    | '/_app/import'
    | '/_app/members'
    | '/_app/onboarding'
    | '/_app/overview'
    | '/_app/pricing'
    | '/_app/recurring'
    | '/_app/settings'
    | '/_app/templates'
    | '/_auth/callback'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/invite/$token'
    | '/_app/'
    | '/_app/expenses/$expenseId'
    | '/_app/expenses/new'
    | '/_app/expenses/'
    | '/_app/groups/'
    | '/_app/expenses/$expenseId/edit'
    | '/_app/groups/$groupId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/callback': {
      id: '/_auth/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recurring': {
      id: '/_app/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof AppRecurringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funds': {
      id: '/_app/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof AppFundsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/breakdown': {
      id: '/_app/breakdown'
      path: '/breakdown'
      fullPath: '/breakdown'
      preLoaderRoute: typeof AppBreakdownRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/new': {
      id: '/_app/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof AppExpensesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/$expenseId': {
      id: '/_app/expenses/$expenseId'
      path: '/expenses/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof AppExpensesExpenseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$groupId/edit': {
      id: '/_app/groups/$groupId/edit'
      path: '/groups/$groupId/edit'
      fullPath: '/groups/$groupId/edit'
      preLoaderRoute: typeof AppGroupsGroupIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/$expenseId/edit': {
      id: '/_app/expenses/$expenseId/edit'
      path: '/edit'
      fullPath: '/expenses/$expenseId/edit'
      preLoaderRoute: typeof AppExpensesExpenseIdEditRouteImport
      parentRoute: typeof AppExpensesExpenseIdRoute
    }
  }
}

interface AppExpensesExpenseIdRouteChildren {
  AppExpensesExpenseIdEditRoute: typeof AppExpensesExpenseIdEditRoute
}

const AppExpensesExpenseIdRouteChildren: AppExpensesExpenseIdRouteChildren = {
  AppExpensesExpenseIdEditRoute: AppExpensesExpenseIdEditRoute,
}

const AppExpensesExpenseIdRouteWithChildren =
  AppExpensesExpenseIdRoute._addFileChildren(AppExpensesExpenseIdRouteChildren)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBreakdownRoute: typeof AppBreakdownRoute
  AppFundsRoute: typeof AppFundsRoute
  AppImportRoute: typeof AppImportRoute
  AppMembersRoute: typeof AppMembersRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppPricingRoute: typeof AppPricingRoute
  AppRecurringRoute: typeof AppRecurringRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExpensesExpenseIdRoute: typeof AppExpensesExpenseIdRouteWithChildren
  AppExpensesNewRoute: typeof AppExpensesNewRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
  AppGroupsGroupIdEditRoute: typeof AppGroupsGroupIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBreakdownRoute: AppBreakdownRoute,
  AppFundsRoute: AppFundsRoute,
  AppImportRoute: AppImportRoute,
  AppMembersRoute: AppMembersRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppPricingRoute: AppPricingRoute,
  AppRecurringRoute: AppRecurringRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
  AppExpensesExpenseIdRoute: AppExpensesExpenseIdRouteWithChildren,
  AppExpensesNewRoute: AppExpensesNewRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
  AppGroupsGroupIdEditRoute: AppGroupsGroupIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
