/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthCallbackRouteImport } from './routes/_auth/callback'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppMembersRouteImport } from './routes/_app/members'
import { Route as AppBreakdownRouteImport } from './routes/_app/breakdown'
import { Route as AppExpensesIndexRouteImport } from './routes/_app/expenses/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppBreakdownRoute = AppBreakdownRouteImport.update({
  id: '/breakdown',
  path: '/breakdown',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/breakdown': typeof AppBreakdownRoute
  '/members': typeof AppMembersRoute
  '/settings': typeof AppSettingsRoute
  '/callback': typeof AuthCallbackRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/expenses/': typeof AppExpensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/breakdown': typeof AppBreakdownRoute
  '/members': typeof AppMembersRoute
  '/settings': typeof AppSettingsRoute
  '/callback': typeof AuthCallbackRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/expenses': typeof AppExpensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/breakdown': typeof AppBreakdownRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/callback': typeof AuthCallbackRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/breakdown'
    | '/members'
    | '/settings'
    | '/callback'
    | '/login'
    | '/signup'
    | '/expenses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/breakdown'
    | '/members'
    | '/settings'
    | '/callback'
    | '/login'
    | '/signup'
    | '/expenses'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/breakdown'
    | '/_app/members'
    | '/_app/settings'
    | '/_auth/callback'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/'
    | '/_app/expenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/callback': {
      id: '/_auth/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/breakdown': {
      id: '/_app/breakdown'
      path: '/breakdown'
      fullPath: '/breakdown'
      preLoaderRoute: typeof AppBreakdownRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBreakdownRoute: typeof AppBreakdownRoute
  AppMembersRoute: typeof AppMembersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBreakdownRoute: AppBreakdownRoute,
  AppMembersRoute: AppMembersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
