import type { ExpenseWithParticipants } from '@commune/types';
import { supabase } from './client';
import { ensureExpenseCycleOpen, ensureGroupCycleOpenForDate } from './cycles';
import {
  buildWorkspaceBillingReport,
  addUtcDays,
  toDateKey,
  toMonthKey,
  type WorkspaceBillingExpenseRecord,
  type WorkspaceBillingReport,
} from './workspace-billing';

/**
 * Returns the current month key in 'YYYY-MM' format.
 */
export function getCurrentMonthKey(referenceDate = new Date()): string {
  return toMonthKey(referenceDate);
}

/**
 * Calculates the due date for a generated recurring expense based on the
 * source expense's recurrence type and original due date.
 */
export function computeRecurringDueDate(
  recurrenceType: string,
  sourceDueDate: string,
  referenceDate = new Date(),
): string {
  const sourceDate = new Date(`${sourceDueDate}T00:00:00.000Z`);
  if (Number.isNaN(sourceDate.getTime())) {
    return toDateKey(referenceDate);
  }

  if (recurrenceType === 'monthly') {
    const year = referenceDate.getUTCFullYear();
    const month = referenceDate.getUTCMonth();
    // Clamp day to the last day of the current month
    const lastDay = new Date(Date.UTC(year, month + 1, 0)).getUTCDate();
    const day = Math.min(sourceDate.getUTCDate(), lastDay);
    return toDateKey(new Date(Date.UTC(year, month, day)));
  }

  if (recurrenceType === 'weekly') {
    const sourceDayOfWeek = sourceDate.getUTCDay();
    const todayDayOfWeek = referenceDate.getUTCDay();
    let daysUntilNext = sourceDayOfWeek - todayDayOfWeek;
    if (daysUntilNext <= 0) daysUntilNext += 7;
    return toDateKey(addUtcDays(referenceDate, daysUntilNext));
  }

  // Fallback — use today
  return toDateKey(referenceDate);
}

function computeDueDate(
  recurrenceType: string,
  sourceDueDate: string,
): string {
  return computeRecurringDueDate(recurrenceType, sourceDueDate);
}

function shiftDateByDueDateDelta(
  date: string | null,
  sourceDueDate: string,
  nextDueDate: string,
): string | null {
  if (!date) return null;

  const sourceDue = new Date(`${sourceDueDate}T00:00:00.000Z`);
  const nextDue = new Date(`${nextDueDate}T00:00:00.000Z`);
  const original = new Date(`${date}T00:00:00.000Z`);
  const deltaDays = Math.round(
    (nextDue.getTime() - sourceDue.getTime()) / (1000 * 60 * 60 * 24),
  );

  original.setUTCDate(original.getUTCDate() + deltaDays);
  return toDateKey(original);
}

export interface PausedRecurringExpenseState {
  recurrence_type: string;
  recurrence_interval: number;
  description: string | null;
}

const PAUSED_RECURRING_EXPENSE_PATTERN = /\[paused:([^\]:]+)(?::(\d+))?\]/;

export function parsePausedRecurringExpenseState(
  description: string | null | undefined,
): PausedRecurringExpenseState | null {
  const rawDescription = description ?? '';
  const match = rawDescription.match(PAUSED_RECURRING_EXPENSE_PATTERN);
  if (!match) return null;

  const recurrenceInterval = Number.parseInt(match[2] ?? '1', 10);
  const cleanedDescription = rawDescription
    .replace(PAUSED_RECURRING_EXPENSE_PATTERN, '')
    .replace(/\s{2,}/g, ' ')
    .trim();

  return {
    recurrence_type: match[1]!,
    recurrence_interval: Number.isFinite(recurrenceInterval) && recurrenceInterval > 0
      ? recurrenceInterval
      : 1,
    description: cleanedDescription || null,
  };
}

/**
 * Generate recurring expenses for a group. For each expense with a non-null,
 * non-'none' recurrence, checks if a generated copy already exists for the
 * current month in `recurring_expense_log`. If not, creates a new expense
 * copying all relevant fields, participants, and payment records.
 *
 * Returns an array of newly generated expense IDs.
 */
export async function generateRecurringExpenses(
  groupId: string,
): Promise<string[]> {
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) throw new Error('Not authenticated');

  const currentMonth = getCurrentMonthKey();

  // 1. Fetch IDs of expenses that were themselves generated by recurrence so
  //    we can exclude them — only original source expenses should spawn copies.
  const { data: generatedRows, error: genError } = await supabase
    .from('recurring_expense_log')
    .select('generated_expense_id');

  if (genError) throw genError;

  const generatedExpenseIds = new Set(
    (generatedRows ?? []).map(
      (r: { generated_expense_id: string }) => r.generated_expense_id,
    ),
  );

  // 2. Fetch all active recurring expenses in the group
  const { data: allRecurring, error: fetchError } = await supabase
    .from('expenses')
    .select(
      `
      *,
      participants:expense_participants(*)
    `,
    )
    .eq('group_id', groupId)
    .eq('is_active', true)
    .neq('recurrence_type', 'none');

  if (fetchError) throw fetchError;

  // Filter out any expense that was itself generated — only true sources remain
  const recurringExpenses = (allRecurring ?? []).filter(
    (e: { id: string }) => !generatedExpenseIds.has(e.id),
  );

  if (recurringExpenses.length === 0) return [];

  // 3. Check which ones already have a log entry for this month
  const sourceIds = recurringExpenses.map((e: { id: string }) => e.id);

  const { data: existingLogs, error: logError } = await supabase
    .from('recurring_expense_log')
    .select('source_expense_id')
    .in('source_expense_id', sourceIds)
    .eq('generated_for_month', currentMonth);

  if (logError) throw logError;

  const alreadyGenerated = new Set(
    (existingLogs ?? []).map(
      (log: { source_expense_id: string }) => log.source_expense_id,
    ),
  );

  // 4. Generate missing expenses
  const generatedIds: string[] = [];

  for (const source of recurringExpenses as (Record<string, unknown> & {
    id: string;
    title: string;
    amount: number;
    category: string;
    description: string | null;
    currency: string;
    split_method: string;
    group_id: string;
    created_by: string;
    recurrence_type: string;
    recurrence_interval: number;
    due_date: string;
    vendor_name: string | null;
    invoice_reference: string | null;
    invoice_date: string | null;
    payment_due_date: string | null;
    paid_by_user_id: string | null;
    participants: {
      user_id: string;
      share_amount: number;
      share_percentage: number | null;
    }[];
  })[]) {
    if (alreadyGenerated.has(source.id)) continue;

    const dueDate = computeDueDate(source.recurrence_type, source.due_date);
    const invoiceDate = shiftDateByDueDateDelta(
      source.invoice_date,
      source.due_date,
      dueDate,
    );
    const paymentDueDate = shiftDateByDueDateDelta(
      source.payment_due_date,
      source.due_date,
      dueDate,
    );

    await ensureGroupCycleOpenForDate(
      source.group_id,
      dueDate,
      'generate recurring expenses for this cycle',
    );

    // Insert the new expense
    const { data: newExpense, error: insertError } = await supabase
      .from('expenses')
      .insert({
        title: source.title,
        amount: source.amount,
        category: source.category,
        description: source.description,
        currency: source.currency,
        split_method: source.split_method,
        vendor_name: source.vendor_name,
        invoice_reference: source.invoice_reference,
        invoice_date: invoiceDate,
        payment_due_date: paymentDueDate,
        group_id: source.group_id,
        created_by: source.created_by,
        recurrence_type: 'none',
        recurrence_interval: 0,
        due_date: dueDate,
        paid_by_user_id: source.paid_by_user_id,
      })
      .select()
      .single();

    if (insertError) throw insertError;

    const newExpenseId = (newExpense as { id: string }).id;

    // Copy participants
    const participants = source.participants.map((p) => ({
      expense_id: newExpenseId,
      user_id: p.user_id,
      share_amount: p.share_amount,
      share_percentage: p.share_percentage,
    }));

    const { error: participantError } = await supabase
      .from('expense_participants')
      .insert(participants);

    if (participantError) {
      // Roll back the expense on participant insert failure
      await supabase
        .from('expenses')
        .update({ is_active: false })
        .eq('id', newExpenseId);
      throw participantError;
    }

    // Note: payment_records are auto-created by the trg_create_payment_record
    // trigger when expense_participants are inserted, so no manual insert needed.

    // Log the generation
    const { error: logInsertError } = await supabase
      .from('recurring_expense_log')
      .insert({
        source_expense_id: source.id,
        generated_expense_id: newExpenseId,
        generated_for_month: currentMonth,
      });

    if (logInsertError) throw logInsertError;

    generatedIds.push(newExpenseId);
  }

  return generatedIds;
}

/**
 * Returns all active expenses in the group that have a non-'none' recurrence.
 */
export async function getRecurringExpenses(
  groupId: string,
): Promise<ExpenseWithParticipants[]> {
  // First get IDs of generated expenses so we can exclude them
  const { data: generatedRows } = await supabase
    .from('recurring_expense_log')
    .select('generated_expense_id');

  const generatedIds = new Set(
    (generatedRows ?? []).map((r: { generated_expense_id: string }) => r.generated_expense_id),
  );

  const { data, error } = await supabase
    .from('expenses')
    .select(
      `
      *,
      participants:expense_participants(
        *,
        user:users(*)
      ),
      payment_records(*),
      paid_by_user:users!expenses_paid_by_user_id_fkey(*)
    `,
    )
    .eq('group_id', groupId)
    .eq('is_active', true)
    .neq('recurrence_type', 'none')
    .order('due_date', { ascending: false });

  if (error) throw error;

  // Filter out generated copies — only show true source expenses
  const sources = (data ?? []).filter(
    (e: { id: string }) => !generatedIds.has(e.id),
  );

  return sources as unknown as ExpenseWithParticipants[];
}

/**
 * Returns an export-ready workspace billing report for all recurring expenses
 * in the group. This is useful for surfacing shared subscriptions and tool
 * costs without duplicating the dashboard/analytics plumbing.
 */
export async function getRecurringWorkspaceBillingReport(
  groupId: string,
): Promise<WorkspaceBillingReport> {
  const recurringExpenses = await getRecurringExpenses(groupId);
  return buildWorkspaceBillingReport(recurringExpenses as WorkspaceBillingExpenseRecord[]);
}

/**
 * Pause a recurring expense by setting its recurrence_type to 'none'.
 * The original recurrence type is stored in the description field as a tag
 * so it can be restored on resume.
 */
export async function pauseRecurringExpense(expenseId: string): Promise<void> {
  await ensureExpenseCycleOpen(expenseId, 'pause a recurring expense in this cycle');

  // Fetch the current expense to save original recurrence info
  const { data: expense, error: fetchError } = await supabase
    .from('expenses')
    .select('recurrence_type, recurrence_interval, description')
    .eq('id', expenseId)
    .single();

  if (fetchError) throw fetchError;

  const originalType = expense.recurrence_type;
  if (originalType === 'none') return; // Already paused

  // Store original type as a tag in description so we can resume later
  const originalInterval = Math.max(1, expense.recurrence_interval ?? 1);
  const pauseTag = `[paused:${originalType}:${originalInterval}]`;
  const currentDesc = expense.description ?? '';
  const newDesc = currentDesc.includes('[paused:')
    ? currentDesc
    : `${pauseTag}${currentDesc ? ' ' + currentDesc : ''}`;

  const { error } = await supabase
    .from('expenses')
    .update({ recurrence_type: 'none', recurrence_interval: 0, description: newDesc })
    .eq('id', expenseId);

  if (error) throw error;
}

/**
 * Resume a paused recurring expense by restoring its original recurrence_type.
 */
export async function resumeRecurringExpense(expenseId: string): Promise<void> {
  await ensureExpenseCycleOpen(expenseId, 'resume a recurring expense in this cycle');

  const { data: expense, error: fetchError } = await supabase
    .from('expenses')
    .select('description')
    .eq('id', expenseId)
    .single();

  if (fetchError) throw fetchError;

  const pausedState = parsePausedRecurringExpenseState(expense.description);
  if (!pausedState) return; // No pause tag found

  const { error } = await supabase
    .from('expenses')
    .update({
      recurrence_type: pausedState.recurrence_type,
      recurrence_interval: pausedState.recurrence_interval,
      description: pausedState.description,
    })
    .eq('id', expenseId);

  if (error) throw error;
}

/**
 * Archive (soft-delete) a recurring expense.
 */
export async function archiveRecurringExpense(expenseId: string): Promise<void> {
  await ensureExpenseCycleOpen(expenseId, 'archive a recurring expense in this cycle');

  const { error } = await supabase
    .from('expenses')
    .update({ is_active: false })
    .eq('id', expenseId);

  if (error) throw error;
}

/**
 * Returns paused recurring expenses for a group (recurrence_type='none' but have a pause tag).
 */
export async function getPausedRecurringExpenses(
  groupId: string,
): Promise<ExpenseWithParticipants[]> {
  const { data, error } = await supabase
    .from('expenses')
    .select(
      `
      *,
      participants:expense_participants(
        *,
        user:users(*)
      ),
      payment_records(*),
      paid_by_user:users!expenses_paid_by_user_id_fkey(*)
    `,
    )
    .eq('group_id', groupId)
    .eq('is_active', true)
    .eq('recurrence_type', 'none')
    .like('description', '%[paused:%')
    .order('due_date', { ascending: false });

  if (error) throw error;
  return data as unknown as ExpenseWithParticipants[];
}
